blogicum/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path(
        '',
        views.IndexListView.as_view(),
        name='index'
    ),
    path(
        'posts/<int:post_id>/',
        views.PostDetailView.as_view(),
        name='post_detail'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.PostUpdateView.as_view(),
        name='edit_post'
    ),
    path(
        'posts/<int:post_id>/delete/',
        views.PostDeleteView.as_view(),
        name='delete_post'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.CommentCreateView.as_view(),
        name='add_comment'
    ),
    path(
        'posts/create/',
        views.CreatePostView.as_view(),
        name='create_post'
    ),
    path(
        'posts/<int:post_id>/edit_comment/<int:comment_id>/',
        views.CommentUpdateView.as_view(),
        name='edit_comment'
    ),
    path(
        'posts/<int:post_id>/delete_comment/<int:comment_id>/',
        views.CommentDeleteView.as_view(),
        name='delete_comment'
    ),
    path(
        'category/<slug:category_slug>/',
        views.CategoryDetailView.as_view(),
        name='category_posts'
    ),
    path(
        'profile/<slug:username>/',
        views.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'profile/<slug:username>/edit/',
        views.ProfileEditView.as_view(),
        name='edit_profile'
    ),
]

blogicum/blogicum/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('pages/', include('pages.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/registration/', include('users.urls')),
]

handler403 = 'pages.views.csrf_failure'

handler404 = 'pages.views.page_not_found'

handler500 = 'pages.views.internal_error'

if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogicum/templates/pages/403csrf.html
{% extends "base.html" %}
{% block title %}Ошибка CSRF токена{% endblock %}
{% block content %}
  <h1>Ошибка CSRF токена. 403</h1>
  <a href="{% url 'blog:index' %}">Вернуться на главную</a>
{% endblock %}

blogicum/templates/pages/about.html
{% extends "base.html" %}
{% block title %}
  О проекте
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        О проекте
      </div>
      <div class="card-body">
        <p>
          Блогикум — это дом для творческих людей. Это — сообщество людей, для которых
          нет грани между ведением блога и дружбой в социальных сетях.
        </p>
        <p>
          Дружба и рассказы о новых, неизведанных впечатлениях — вот
          что вы найдете на нашем ресурсе. Миллионы блогов по различным темам.
          Путешествия, политика, развлечения, мода, литература, дизайн и все
          другие сферы человеческой деятельности.
        </p>
        <p>
          Творчество, разнообразие и свобода взглядов и самовыражения —
          основные черты наших пользователей.
        </p>
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/pages/rules.html
{% extends "base.html" %}
{% block title %}
  Наши правила
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Правила сайта
      </div>
      <div class="card-body">
        <p>
          <b>Cамовыражение.</b> У наших пользователей должна
          быть возможность создать что-то своё, выразить себя,
          свои мысли и чувства.
        </p>
        <p>
          <b>Многообразие.</b> Мы уважаем и приветствуем разные
          мнения и культуры. Блогикум — это место, объединяющее
          самых разных людей. Поделитесь своим уникальным взглядом на мир.
        </p>
        <p>
          <b>Творчество.</b> Не важно, в какой области вы творите,
          это может быть литература, дизайн, программирование.
          Наши инструменты помогут вам раскрыть талант максимально
          просто и комфортно.
        </p>
        <p>
          <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне.
          Делитесь своей информацией только с теми, кого выбрали.
          Как и насколько засекречивать вашу личную информацию —
          определяете вы и только вы.
        </p>
      </div>
    </div>
  </div>
{% endblock %}